import os

depts = [
    ('dept_001', 'Resume Intelligence', 'resume_intelligence', 'Resume parsing, structural validation, action verb audit, ATS optimization, date gap detection, scoring, and orchestrations.'),
    ('dept_002', 'ATS Optimization', 'ats_optimization', 'Hard/soft skill keyword matching, ATS format compatibility, section header auditing, weak phrase detection, quantification metering, and ATS scoring.'),
    ('dept_003', 'Job Intelligence', 'job_intelligence', 'Job Description parsing, technical stack extraction, seniority level classification, responsibility parsing, salary benchmarking, work model extraction, and domain complexity scoring.'),
    ('dept_004', 'Company Intelligence', 'company_intelligence', 'Company culture evaluation, engineering values audit, tech stack overlap matching, news sentiment tracking, interview focus profiling, and Tavily web research.'),
    ('dept_005', 'Skill Gap Intelligence', 'skill_gap_intelligence', 'Candidate vs JD skill gap extraction, missing hard/soft skill identification, learning priority matrix calculation, course recommendation mapping, and time-to-proficiency metering.'),
    ('dept_006', 'Interview Intelligence', 'interview_intelligence', 'Role-specific technical Q&A generation, behavioral question synthesis, STAR method answer structuring, response quality scoring, mock interview simulation, and speech filler word auditing.'),
    ('dept_007', 'Career Roadmap', 'career_roadmap', '30-60-90 day milestone career plan generation, target role progression mapping, skill milestone scheduling, salary trajectory modeling, certification roadmap planning, and execution risk calculation.'),
    ('dept_008', 'Career Analytics', 'career_analytics', 'Overall readiness score aggregation, market competitiveness calculation, domain skill radar generation, benchmark percentile scoring, career velocity index calculation, and weak point identification.'),
    ('dept_009', 'Memory & Personalization', 'memory_personalization', 'Candidate preference tracking, historical skill mastery logging, context retention management, personal career goal tracking, interaction history indexing, and prompt personalization.'),
    ('dept_010', 'Market Trend Intelligence', 'market_trend_intelligence', 'Live tech demand indexing, emerging skill trend detection, remote work ratio tracking, compensation market benchmarking, hiring volume indexing, and skill obsolescence warning.'),
    ('dept_011', 'Document Verification', 'document_verification', 'Employment date gap auditing, degree credential verification, formatting inconsistency detection, contact info validation, bullet point metric verification, and document authenticity scoring.'),
    ('dept_012', 'Portfolio Intelligence', 'portfolio_intelligence', 'GitHub repository impact auditing, project tech stack evaluation, code quality assessment, portfolio project gap identification, automated README generation, and deployment verification.'),
    ('dept_013', 'Communication Intelligence', 'communication_intelligence', 'Recruiter outreach cold email drafting, LinkedIn connection message tailoring, post-interview follow-up generation, salary negotiation script drafting, thank-you note synthesis, and tone & politeness auditing.'),
    ('dept_014', 'Technical Skill Verification', 'technical_skill_verification', 'Coding syntax verification, framework mastery scoring, system design skill evaluation, algorithmic problem solving auditing, git workflow proficiency metering, and technical confidence scoring.'),
    ('dept_015', 'Peer Benchmarking', 'peer_benchmarking', 'Applicant cohort percentile ranking, peer skill overlap scoring, resume impact comparison, competitive tier classification, experience level normalization, and differentiation metric metering.'),
    ('dept_016', 'Offer & Salary Negotiation', 'offer_salary_negotiation', 'Compensation package breakdown, cost of living adjustment metering, equity & stock option valuation, counter-offer script generation, total rewards comparison, and negotiation leverage scoring.'),
    ('dept_017', 'Alumni Network Intelligence', 'alumni_network_intelligence', 'Target company alumni mapping, warm referral path identification, alumni outreach template generation, shared background connection scoring, response rate prediction, and referral pipeline tracking.'),
    ('dept_018', 'Mentorship Intelligence', 'mentorship_intelligence', 'Industry mentor matching score, mentorship goal alignment, session topic recommendation, feedback loop tracking, mentorship availability scheduling, and career guidance synthesis.'),
    ('dept_019', 'Freelance & Gig Intelligence', 'freelance_gig_intelligence', 'Freelance platform profile auditing, gig rate hourly benchmarking, proposal pitch drafting, client feedback sentiment analysis, portfolio contract project selection, and freelance revenue modeling.'),
    ('dept_020', 'Personal Branding Intelligence', 'personal_branding_intelligence', 'LinkedIn headline & summary optimization, personal brand clarity scoring, technical blog topic recommendation, public presence engagement auditing, thought leadership content generation, and brand consistency scoring.'),
    ('dept_021', 'Leadership & Management Intelligence', 'leadership_management_intelligence', 'Engineering leadership signal extraction, team management scenario evaluation, strategic decision auditing, cross-functional collaboration scoring, delegation framework analysis, and executive leadership readiness.'),
    ('dept_022', 'Executive Communication', 'executive_communication', 'Executive summary conciseness auditing, C-suite presentation deck structure, strategic tone alignment, board memo drafting, crisis communication framing, and executive presence scoring.'),
    ('dept_023', 'Startup & Entrepreneurship', 'startup_entrepreneurship', 'Founding team skill balance scoring, pitch deck slide auditing, MVP feature prioritization, market sizing TAM/SAM estimation, investor QA preparation, and startup traction scoring.'),
    ('dept_024', 'Product Management Intelligence', 'product_management_intelligence', 'PRD requirement audit, user story & acceptance criteria scoring, feature prioritization RICE framework metering, product metric KPI definition, competitor feature comparison, and PM interview case evaluation.'),
    ('dept_025', 'Data Science & AI Intelligence', 'data_science_ai_intelligence', 'ML model evaluation metric auditing, data pipeline ETL architecture review, statistical experiment design scoring, SQL & pandas code efficiency auditing, AI project business value estimation, and MLOps readiness scoring.'),
    ('dept_026', 'Cybersecurity & Compliance', 'cybersecurity_compliance', 'Security audit compliance verification, threat modeling analysis, vulnerability assessment scoring, security certification roadmap tracking, IAM policy audit, and cybersecurity incident simulation.'),
    ('dept_027', 'Cloud & DevOps Engineering', 'cloud_devops_engineering', 'Infrastructure as Code Terraform audit, CI/CD pipeline efficiency scoring, Kubernetes cluster architecture evaluation, cloud cost optimization analysis, site reliability SRE metric auditing, and cloud security compliance.'),
    ('dept_028', 'Mobile App Development', 'mobile_app_development', 'iOS Swift / Android Kotlin code quality audit, mobile UI response time evaluation, app store optimization ASO score, cross-platform React Native evaluation, mobile security audit, and app store release readiness.'),
    ('dept_029', 'UI/UX Design Intelligence', 'ui_ux_design_intelligence', 'Design portfolio case study audit, Figma design system usage scoring, user research methodology evaluation, accessibility WCAG design audit, interaction micro-animation review, and UX wireframe clarity scoring.'),
    ('dept_030', 'Software Architecture Intelligence', 'software_architecture_intelligence', 'Microservices vs Monolith trade-off evaluation, design pattern audit, database schema scalability review, API contract design scoring, system bottleneck detection, and enterprise architecture readiness.'),
    ('dept_031', 'API Design Intelligence', 'api_design_intelligence', 'RESTful / GraphQL schema contract validation, OpenAPI spec compliance audit, API rate limiting & throttling metering, payload optimization scoring, authentication JWT/OAuth review, and API documentation clarity scoring.'),
    ('dept_032', 'Database Intelligence', 'database_intelligence', 'SQL query execution plan indexing audit, database normalization scoring, NoSQL data modeling evaluation, query latency optimization metering, backup DRP compliance review, and database scalability scoring.'),
    ('dept_033', 'Machine Learning Engineering', 'ml_engineering', 'Model training pipeline latency audit, hyperparameter optimization scoring, feature store architecture review, model drift monitoring metering, GPU utilization efficiency auditing, and ML inference deployment scoring.'),
    ('dept_034', 'NLP Intelligence', 'nlp_intelligence', 'Text embeddings vector search quality audit, LLM prompt token optimization scoring, RAG retrieval accuracy evaluation, sentiment analysis classification auditing, NER entity extraction metering, and NLP model benchmark scoring.'),
    ('dept_035', 'Search & Recommendation Intelligence', 'search_recommendation_intelligence', 'BM25 / Vector hybrid search relevance audit, recommendation system CTR scoring, personalized ranking algorithm evaluation, search query latency metering, cold start handling review, and search precision score.'),
    ('dept_036', 'Analytics Intelligence', 'analytics_intelligence', 'User funnel conversion tracking audit, cohort retention analysis scoring, A/B test statistical significance review, event tracking taxonomy evaluation, dashboard metric visualization review, and product analytics score.'),
    ('dept_037', 'Infrastructure Monitoring Intelligence', 'infrastructure_monitoring_intelligence', 'Prometheus / Grafana metric alert rule audit, log aggregation error rate scoring, APM trace latency distribution review, incident response MTTR metering, uptime SLA compliance review, and observability score.'),
    ('dept_038', 'Content Intelligence', 'content_intelligence', 'SEO content optimization score, readability grade level audit, brand voice consistency review, content plagiarism & originality audit, social media engagement predictor, and content marketing score.'),
    ('dept_039', 'User Onboarding Intelligence', 'user_onboarding_intelligence', 'First-time user onboarding drop-off audit, time-to-first-value TTFV metering, feature tour completion rate scoring, user activation milestone review, welcome email flow evaluation, and onboarding conversion score.'),
    ('dept_040', 'Notification Intelligence', 'notification_intelligence', 'Push notification click-through rate audit, email deliverability score, notification fatigue & frequency metering, channel preference optimization review, automated alert timing review, and notification engagement score.'),
    ('dept_041', 'Privacy & Data Governance', 'privacy_data_governance', 'GDPR / CCPA data privacy compliance audit, PII data masking verification score, data retention policy enforcement review, consent management audit, data lineage tracking review, and privacy audit score.'),
    ('dept_042', 'Performance Optimization Intelligence', 'performance_optimization_intelligence', 'Lighthouse Web Vitals performance audit, bundle size asset compression review, server response time TTFB metering, memory leak detection audit, caching policy strategy review, and frontend speed score.'),
    ('dept_043', 'Testing & Quality Assurance Intelligence', 'testing_qa_intelligence', 'Automated test suite code coverage audit, regression test suite pass rate scoring, end-to-end Playwright/Cypress test evaluation, unit test assertion quality review, bug report severity classifier, and QA readiness score.'),
    ('dept_044', 'Internationalization & Localization Intelligence', 'i18n_l10n_intelligence', 'i18n string extraction completeness audit, multi-language translation accuracy score, date/currency locale formatting review, RTL layout compatibility audit, localized content engagement review, and L10n readiness score.'),
    ('dept_045', 'Accessibility & Inclusivity Intelligence', 'accessibility_inclusivity_intelligence', 'WCAG 2.1 AA screen reader compliance audit, keyboard navigation accessibility score, color contrast ratio verification review, ARIA landmark tag audit, inclusive language audit, and universal access score.'),
    ('dept_046', 'Billing & Monetization Intelligence', 'billing_monetization_intelligence', 'Subscription MRR / ARR revenue tracking audit, Stripe webhook payment retry success score, invoice generation accuracy review, dunning management churn reduction audit, pricing tier conversion review, and monetization score.'),
    ('dept_047', 'Customer Support & Success Intelligence', 'customer_support_success', 'First response time FRT support ticket audit, customer satisfaction CSAT score, Zendesk/Intercom ticket resolution review, churn risk prediction indicator audit, knowledge base article accuracy review, and support excellence score.'),
    ('dept_048', 'Sales & Revenue Intelligence', 'sales_revenue_intelligence', 'Sales CRM deal stage pipeline velocity audit, win/loss conversion rate scoring, outbound sales cadence response review, ACV contract value optimization audit, sales rep quota attainment review, and revenue generation score.'),
    ('dept_049', 'Partner & Ecosystem Intelligence', 'partner_ecosystem_intelligence', 'Channel partner referral deal volume audit, API integration ecosystem health score, co-marketing campaign performance review, partner portal engagement review, joint solution validation review, and ecosystem growth score.'),
    ('dept_050', 'Learning & Course Intelligence', 'learning_course_intelligence', 'Student course completion rate tracking audit, quiz score assessment accuracy review, video watch time engagement metering, learning path milestone progression review, curriculum relevance score, and learning intelligence score.'),
    ('dept_051', 'Assessment & Certification Intelligence', 'assessment_certification_intelligence', 'Certification exam question proctoring audit, skill badge verification authenticity score, rubric scoring consistency evaluation, certificate expiration reminder audit, exam difficulty discrimination index review, and certification score.'),
    ('dept_052', 'Internship & Co-op Intelligence', 'internship_coop_intelligence', 'Internship placement rate tracking audit, employer co-op evaluation score, student internship learning log review, mentor check-in frequency audit, return offer conversion rate review, and internship success score.'),
    ('dept_053', 'University & Campus Relations', 'university_campus_relations', 'University career fair employer turnout audit, campus recruiting partnership score, career center liaison activity review, student attendance career event audit, university relations ROI review, and campus partnership score.'),
    ('dept_054', 'Academic Advising Intelligence', 'academic_advising_intelligence', 'Degree progress audit tracking, student GPA trajectory forecasting score, prerequisite registration block check review, advising appointment satisfaction audit, graduation timeline risk classifier, and advising excellence score.'),
    ('dept_055', 'Student Financial Aid Intelligence', 'student_financial_aid_intelligence', 'FAFSA verification application tracking audit, institutional scholarship disbursement score, financial aid award letter clarity review, student loan counseling completion audit, work-study job placement review, and financial aid score.'),
    ('dept_056', 'Research & Publication Intelligence', 'research_publication_intelligence', 'Academic research paper citation count audit, peer-reviewed journal impact factor score, co-authorship collaboration network review, research grant application review audit, conference presentation tracker, and publication score.'),
    ('dept_057', 'Campus Housing & Facilities Intelligence', 'campus_facilities_intelligence', 'Residence hall room occupancy tracking audit, facility maintenance work order turnaround score, campus energy consumption sustainability review, keycard access security audit, room assignment satisfaction review, and facilities score.'),
    ('dept_058', 'Student Health & Wellness Intelligence', 'health_counseling_services', 'Campus health center appointment volume audit, student immunization compliance score, mental health counseling intake wait time review, wellness workshop attendance audit, medical leave processing review, and wellness score.'),
    ('dept_059', 'Global Study Abroad Intelligence', 'global_study_abroad_intelligence', 'Study abroad program application tracking audit, international visa approval compliance score, global partner university course credit evaluation review, emergency travel alert audit, study abroad satisfaction review, and study abroad score.'),
    ('dept_060', 'Alumni Mentorship & Engagement', 'alumni_mentorship_engagement', 'Alumni mentor active partnership tracking audit, alumni giving participation rate score, homecoming event registration review, alumni career networking directory audit, alumni engagement index review, and alumni network score.'),
    ('dept_061', 'Parent & Guardian Relations', 'parent_guardian_relations', 'Parent association newsletter open rate audit, family weekend event registration score, parent donor contribution campaign review, emergency contact verification audit, parent satisfaction survey review, and parent relations score.'),
    ('dept_062', 'High School & K-12 Outreach', 'high_school_outreach', 'High school visit campus tour recruitment audit, prospective student inquiry lead volume score, STEM summer camp enrollment review, dual enrollment credit audit, high school counselor relationship review, and outreach score.'),
    ('dept_063', 'Transfer Student Intelligence', 'transfer_student_intelligence', 'Transfer credit articulation agreement audit, community college transfer pathway yield score, transfer orientation attendance review, transfer student retention 1-year audit, transfer advising satisfaction review, and transfer score.'),
    ('dept_064', 'Continuing Education & Executive Ed', 'continuing_executive_ed', 'Executive certificate program enrollment audit, corporate custom training revenue score, non-credit course completion rate review, professional CEU credit audit, executive learner satisfaction review, and continuing ed score.'),
    ('dept_065', 'Campus Safety & Emergency Response', 'campus_safety_emergency', 'Campus police emergency response time audit, blue light phone station uptime score, emergency mass notification test review, Clery Act crime report compliance audit, safety walk escort requests review, and campus safety score.'),
    ('dept_066', 'Disability Services & Accommodations', 'disability_services_accommodations', 'Student accommodation plan registration audit, accessible testing center booth capacity score, digital WCAG course accessibility review, assistive screen reader software audit, CART captioning fulfillment review, and accessibility score.'),
    ('dept_067', 'Veteran & Military Services', 'veteran_military_services', 'GI Bill education benefit processing audit, veteran student lounge check-in score, military transfer credit evaluation review, veteran ROTC commissioning audit, veteran student persistence review, and veteran service score.'),
    ('dept_068', 'International Student Services', 'international_student_services', 'F-1 / J-1 visa SEVIS compliance audit, OPT / CPT employment authorization processing score, international student orientation attendance review, English ELI program success audit, international student satisfaction review, and international service score.'),
    ('dept_069', 'Campus Dining & Food Services', 'dining_auxiliary_enterprises', 'Dining hall meal plan entry volume audit, retail food venue sales revenue score, dietary allergen labeling compliance review, food safety health inspection audit, student dining CSAT review, and dining excellence score.'),
    ('dept_070', 'Student Athletics & Recreation', 'student_athletics_recreation', 'NCAA Academic Progress Rate APR audit, student-athlete graduation success rate GSR score, varsity home game fan attendance review, athletic training room injury rehab audit, sports information broadcast review, and athletics score.'),
    ('dept_071', 'Campus Bookstore & Learning Materials', 'bookstore_learning_materials', 'Course textbook adoption deadline compliance audit, digital inclusive access program enrollment score, student textbook cost savings review, bookstore merchandise net revenue audit, course materials fulfillment review, and bookstore score.'),
    ('dept_072', 'Transportation & Parking Intelligence', 'transportation_parking_intelligence', 'Campus parking permit registration volume audit, shuttle bus route passenger ridership score, EV charging station utilization review, parking violation citation appeal audit, bicycle transit program review, and transportation score.'),
    ('dept_073', 'Student Legal & Advocacy Services', 'student_legal_advocacy', 'Student legal consultation case volume audit, tenant lease agreement review turnarounds score, traffic citation representation review, student legal education workshop audit, legal advocacy satisfaction review, and legal service score.'),
    ('dept_074', 'Campus Childcare & Family Services', 'campus_childcare_services', 'Campus childcare center enrollment capacity audit, student parent childcare subsidy grant score, early childhood teacher ratio review, childcare waiting list management audit, family services satisfaction review, and childcare score.'),
    ('dept_075', 'Diversity Equity & Inclusion', 'dei_intelligence', 'Campus climate DEI survey response audit, underrepresented minority retention rate score, DEI workshop completion tracking review, faculty search committee DEI training audit, affinity group support review, and DEI excellence score.'),
    ('dept_076', 'Student Government & Leadership', 'student_government_leadership', 'SGA campus election voter turnout audit, student activity fee budget allocation score, student legislative resolution review, campus leadership retreat participation audit, student officer governance review, and leadership score.'),
    ('dept_077', 'Greek Life & Student Organizations', 'greek_life_student_orgs', 'Student organization charter registration audit, fraternity & sorority GPA benchmark score, Greek recruitment new member audit, hazing prevention workshop compliance review, student club budget allocation review, and student org score.'),
    ('dept_078', 'Campus Event & Conference Management', 'event_conference_management', 'Campus facility space reservation volume audit, summer conference housing guest revenue score, AV technology setup request fulfillment review, event catering coordination audit, conference client CSAT review, and event management score.'),
    ('dept_079', 'Sustainability & Green Campus', 'sustainability_green_campus', 'STARS campus sustainability rating audit, campus waste diversion recycling rate score, solar renewable energy generation review, greenhouse gas carbon footprint audit, campus garden engagement review, and sustainability score.'),
    ('dept_080', 'Institutional Advancement & Fundraising', 'institutional_advancement_fundraising', 'Endowment total market value tracking audit, annual capital campaign raised amount score, alumni giving participation rate review, planned giving estate bequest audit, major gifts pipeline review, and advancement score.'),
    ('dept_081', 'Alumni Career Services & Networking', 'alumni_career_networking', 'Alumni job board posting volume audit, alumni career coaching session score, alumni mentoring connection review, regional alumni chapter networking event audit, alumni career satisfaction review, and alumni career score.'),
    ('dept_082', 'Campus Dining Auxiliary Enterprises', 'dining_culinary_services', 'Auxiliary enterprise gross revenue audit, campus catering contract fulfillment score, retail dining vendor lease review, campus vending commission audit, auxiliary operation margin review, and auxiliary enterprise score.'),
    ('dept_083', 'Student Housing & Residential Life', 'residential_housing_operations', 'Residence hall bed occupancy rate audit, housing assignment processing turnaround score, RA resident assistant staffing review, housing maintenance work order audit, residence hall programming review, and residential life score.'),
    ('dept_084', 'Student Health & Counseling', 'health_counseling_services', 'Campus counseling intake wait time audit, licensed counselor student ratio score, group therapy session attendance review, 24/7 crisis hotline response audit, EHR HIPAA compliance review, and health counseling score.'),
    ('dept_085', 'Campus Recreation & Wellness', 'campus_rec_wellness', 'Rec center daily turnstile entry audit, intramural sports league team count score, group fitness class attendance review, outdoor adventure trip participation audit, recreation facility CSAT review, and campus recreation score.'),
    ('dept_086', 'Career Center & Student Employment', 'career_center_student_employment', 'Student campus employment job placement audit, career center appointment volume score, resume review turnaround time review, employer campus interview audit, career fair attendance review, and student employment score.'),
    ('dept_087', 'Financial Aid & Scholarships', 'financial_aid_scholarships', 'FAFSA verification completion rate audit, institutional scholarship dollar distribution score, student financial aid appeal turnaround review, work-study payroll audit, financial aid counseling review, and scholarship score.'),
    ('dept_088', 'Registrar & Academic Records', 'registrar_academic_records', 'Student transcript request fulfillment audit, degree audit graduation audit accuracy score, course catalog registration scheduling review, FERPA privacy compliance audit, transfer credit evaluation review, and registrar score.'),
    ('dept_089', 'Admissions & Enrollment Management', 'admissions_enrollment_management', 'Freshmen application volume audit, enrollment yield deposit rate score, holistic review turnaround time review, campus tour visitor conversion audit, CRM recruitment campaign review, and admissions score.'),
    ('dept_090', 'Student Orientation & Transitions', 'orientation_transition_programs', 'Freshmen orientation attendance rate audit, transfer student orientation completion score, FYE seminar course retention review, Welcome Week event check-in audit, parent orientation review, and orientation score.'),
    ('dept_091', 'Student Judicial & Conduct', 'student_judicial_conduct', 'Student conduct case volume audit, hearing officer turnaround time score, sanction completion compliance review, Academic Integrity Board hearing audit, BIT behavioral intervention review, and judicial conduct score.'),
    ('dept_092', 'Dining & Culinary Services', 'dining_culinary_services', 'Culinary nutritional dietary labeling audit, dining health inspection score, local sustainable food sourcing review, retail dining venue revenue audit, student dining CSAT review, and culinary services score.'),
    ('dept_093', 'Residential Housing Operations', 'residential_housing_operations', 'Housing bed occupancy rate audit, housing assignment processing speed score, RA staffing ratio review, maintenance work order turnaround audit, summer conference housing review, and housing operations score.'),
    ('dept_094', 'Student Disability Access', 'student_disability_access', 'Academic accommodation plan volume audit, accessible testing center proctoring score, WCAG 2.1 AA digital accessibility review, assistive screen reader station audit, ADA physical compliance review, and disability access score.'),
    ('dept_095', 'Campus IT & Technology Services', 'campus_it_technology', 'Campus WiFi network SLA uptime audit, IT helpdesk FCR rate score, SOC cybersecurity incident containment review, software license compliance audit, smart classroom AV readiness review, and campus IT score.'),
    ('dept_096', 'Institutional Research & Accreditation', 'institutional_research_accreditation', 'IPEDS federal compliance reporting audit, SACSCOC regional accreditation status score, 6-year graduation retention rate review, SLO program outcome assessment audit, faculty credentials review, and accreditation score.'),
    ('dept_097', 'Faculty Development & Academic Excellence', 'faculty_development_excellence', 'Faculty pedagogy workshop participation audit, Quality Matters online course certification score, research grant funding review, tenure workload equity audit, new faculty mentoring review, and faculty excellence score.'),
    ('dept_098', 'Campus Mental Health Counseling', 'campus_mental_health_counseling', 'Counseling intake appointment wait time audit, counselor to student ratio score, group therapy session attendance review, crisis hotline response time audit, peer mental health outreach review, and mental health score.'),
    ('dept_099', 'Academic Library & Learning Commons', 'academic_library_commons', 'Library physical & digital collection audit, licensed database cost per use score, research consultation satisfaction review, learning commons tutoring sessions audit, open access repository downloads review, and academic library score.'),
    ('dept_100', 'Student Research & Innovation Incubator', 'student_research_innovation', 'Undergraduate active researcher participation audit, student startup incubator seed funding score, patent tech transfer royalty review, makerspace FabLab utilization audit, innovation challenge grant review, and student research score.'),
    ('dept_101', 'Global Engagement & International Partnerships', 'global_engagement_partnerships', 'International student enrollment volume audit, study abroad participation rate score, bilateral MOU partnership agreement review, ELI English language success audit, international faculty exchange review, and global engagement score.'),
    ('dept_102', 'Campus Safety & Security Operations', 'campus_safety_security', 'Sworn campus police response time audit, CCTV blue light station uptime score, emergency mass notification delivery review, RAD crime prevention workshop audit, Safe Walk escort service review, and campus safety score.'),
    ('dept_103', 'Environmental Health & Safety Compliance', 'environmental_health_safety', 'Laboratory chemical inventory labeling audit, OSHA training completion rate score, EPA wastewater discharge compliance review, IBC biosafety protocol audit, fire system inspection review, and EHS compliance score.'),
    ('dept_104', 'Campus Planning & Capital Construction', 'campus_planning_construction', 'Capital project budget compliance audit, LEED green building certification score, campus master plan milestone review, classroom lab utilization audit, deferred maintenance backlog review, and campus planning score.'),
    ('dept_105', 'Community & Civic Engagement', 'community_civic_engagement', 'Service-learning course student enrollment audit, AmeriCorps volunteer service hours score, student voter registration drive review, community partnership MOU audit, social entrepreneurship review, and civic engagement score.'),
    ('dept_106', 'Alumni Advancement & Endowment Management', 'alumni_advancement_endowment', 'Endowment asset market performance audit, capital campaign goal raised score, alumni giving participation rate review, planned giving estate bequest audit, foundation grant review, and advancement score.'),
    ('dept_107', 'Intercollegiate Athletics & NCAA Compliance', 'intercollegiate_athletics_ncaa', 'NCAA Academic Progress Rate APR audit, student-athlete graduation success rate score, NIL deal disclosure compliance review, varsity home game attendance audit, sports medicine review, and intercollegiate athletics score.'),
    ('dept_108', 'Auxiliary Enterprises & Housing Operations', 'auxiliary_enterprises_housing', 'Residence hall bed occupancy rate audit, dining meal plan revenue score, bookstore digital inclusive access review, conference housing revenue audit, maintenance turnaround review, and auxiliary enterprises score.'),
    ('dept_109', 'Procurement, Purchasing & Vendor Contracts', 'procurement_vendor_contracts', 'Purchase order policy compliance audit, MWBE diverse vendor spend score, RFP competitive bidding compliance review, vendor SLA performance audit, p-card audit exception review, and procurement score.'),
    ('dept_110', 'Campus Human Resources & Talent Operations', 'human_resources_talent_ops', 'Faculty & staff recruitment time-to-fill audit, annual staff retention rate score, compensation equity audit review, employee performance review cycle audit, Title IX EEO training review, and human resources score.'),
    ('dept_111', 'Executive Governance & Board of Trustees Intelligence', 'executive_governance_trustees', 'Board of Trustees resolution tracking audit, presidential strategic plan KPI score, university bylaws compliance review, ERM risk register tracking audit, state lobbying review, and executive governance score.')
]

ts_code = "import { AgentMetadata, DepartmentMetadata } from './types';\n\nexport const ALL_DEPARTMENTS: DepartmentMetadata[] = [\n"
all_agents_code = "export const MOCK_AGENTS: AgentMetadata[] = [\n"

for idx, did, name, dirname, desc in [(i+1, d[0], d[1], d[2], d[3]) for i, d in enumerate(depts)]:
    det_agents_names = [
        f"{name} Master Orchestrator",
        f"Strategic {name} Narrative Agent",
        f"{name} Operations Planner Agent",
        f"{name} Metric Auditor 1",
        f"{name} Metric Auditor 2",
        f"{name} Compliance Auditor",
        f"{name} Performance Meter",
        f"{name} CSAT Meter",
        f"{name} System Scorer",
        f"{name} Pipeline Evaluator"
    ]
    
    dept_agents_json = ""
    for a_idx, a_name in enumerate(det_agents_names):
        a_id = f"{dirname}_agent_{a_idx+1}"
        a_type = "Orchestrator" if a_idx == 0 else ("Reasoning" if a_idx in [1, 2] else "Deterministic")
        a_icon = "Cpu" if a_idx == 0 else ("Brain" if a_idx in [1, 2] else "CheckCircle")
        
        dept_agents_json += f"      {{ id: '{a_id}', name: '{a_name}', type: '{a_type}', description: '{desc}', icon: '{a_icon}' }},\n"
        all_agents_code += f"  {{ id: '{a_id}', name: '{did.upper()}: {a_name}', type: '{a_type}', description: '{desc}', icon: '{a_icon}' }},\n"

    ts_code += f"""  {{
    id: '{did}',
    name: '{name}',
    dirname: '{dirname}',
    agents_count: 10,
    tier: 'PRODUCTION READY',
    description: '{desc}',
    agents: [
{dept_agents_json}    ]
  }},
"""

ts_code += "];\n\n"
all_agents_code += "];\n"

full_mock_data = ts_code + all_agents_code

with open(r'd:\CampusOS\frontend\src\lib\mock-data.ts', 'w', encoding='utf-8') as f:
    f.write(full_mock_data)

print("Generated frontend/src/lib/mock-data.ts successfully!")
