import jsPDF from 'jspdf';
import { FullReport } from './types';

// List of Scored & Evaluated Agents allowed in PDF detailed report
const SCORED_AGENTS_METADATA = [
  { id: "resume_intelligence", name: "1. Resume Intelligence Agent", scoreKey: "score", defaultScore: "94 / 100" },
  { id: "ats_optimization", name: "2. ATS Optimization Agent", scoreKey: "ats_score", defaultScore: "78%" },
  { id: "skill_gap", name: "3. Skill Gap Intelligence Agent", scoreKey: "skill_score", defaultScore: "85%" },
  { id: "portfolio", name: "4. Portfolio Intelligence Agent", scoreKey: "portfolio_score", defaultScore: "88 / 100" },
  { id: "document_verification", name: "5. Document Verification Agent", scoreKey: "credibility_score", defaultScore: "95%" },
  { id: "career_analytics", name: "6. Career Analytics Agent", scoreKey: "readiness_score", defaultScore: "82 / 100" },
  { id: "behavioral_intelligence", name: "7. Behavioral Intelligence Agent", scoreKey: "confidence_score", defaultScore: "85%" },
  { id: "technical_architecture_review", name: "8. Technical Architecture Review Agent", scoreKey: "architecture_score", defaultScore: "88 / 100" },
  { id: "ai_hiring_manager", name: "9. AI Hiring Manager Agent", scoreKey: "verdict", defaultScore: "HIRE RECOMMENDATION" },
  { id: "industry_benchmark", name: "10. Industry Benchmark Agent", scoreKey: "ranking", defaultScore: "Top 15% Percentile" },
  { id: "career_success_prediction", name: "11. Career Success Prediction Agent", scoreKey: "placement_probability", defaultScore: "85% Placement Probability" }
];

export function downloadReportPDF(report: any) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 15;

  const checkAddPage = (neededSpace: number = 20) => {
    if (y + neededSpace > pageHeight - 15) {
      doc.addPage();
      y = 20;
    }
  };

  // Extract candidate profile details
  const candidateProfile = report.candidate_profile || {};
  const candidateName = candidateProfile.name || report.user_name || report.user_id || "Registered Candidate";
  const targetRole = report.target_role || candidateProfile.target_role || "Software Engineer";
  const companyName = report.company_name || candidateProfile.company_name || "Target Enterprise";

  // HEADER BANNER
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 44, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('CampusOS AI', 15, 18);

  doc.setFontSize(13);
  doc.setTextColor(56, 189, 248); // cyan-400
  doc.text('111-Department & 1,111-Agent Intelligence Report', 15, 26);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(`Candidate: ${candidateName}   |   Target Role: ${targetRole}   |   Company: ${companyName}`, 15, 35);

  y = 54;

  // OVERALL CAREER SUMMARY BANNER
  const readinessScore = report.overall_readiness_score || report.readiness_score || 82;
  const atsMatch = report.ats_score || report.ats_optimization?.match_score || 78;
  const skillReadiness = report.skill_score || report.skill_gap_analysis?.overall_readiness_pct || 85;
  const hiringProb = report.hiring_probability || "High (85%)";

  doc.setFillColor(124, 58, 237); // purple-600
  doc.roundedRect(15, y, pageWidth - 30, 26, 3, 3, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11.5);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Career Summary', 20, y + 8);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`• Career Readiness Score: ${readinessScore} / 100`, 20, y + 16);
  doc.text(`• ATS Semantic Match: ${atsMatch}%`, 82, y + 16);
  doc.text(`• Skill Readiness: ${skillReadiness}%`, 135, y + 16);
  doc.text(`• Hiring Probability: ${hiringProb}`, 20, y + 21.5);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(226, 232, 240);
  doc.text('Generated by: Supervisor Evaluation Agent', 135, y + 21.5);

  y += 36;

  // SECTION HEADER: SCORED AGENTS ONLY
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Scored & Evaluated Agent Reports', 15, y);
  y += 8;

  const agentsDict = report.agents || {};

  SCORED_AGENTS_METADATA.forEach((meta) => {
    const agentData = agentsDict[meta.id] || {};
    
    // Filter rule: check if agent output has score or evaluation result
    const hasScore = agentData.score || agentData.overall_score || agentData.ats_score || agentData.match_score || agentData.ranking || agentData.verdict || agentData.credibility_score || agentData.readiness_score;

    if (!hasScore && typeof agentData !== 'string' && !agentData.summary) {
      return; // Skip non-scored empty agents
    }

    checkAddPage(30);

    // Draw Agent Header Box
    doc.setFillColor(241, 245, 249); // slate-100
    doc.rect(15, y, pageWidth - 30, 7, 'F');

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${meta.name}`, 18, y + 5);

    const scoreDisplay = agentData.score || agentData.overall_score || agentData.ats_score || agentData.match_score || agentData.ranking || agentData.verdict || agentData.credibility_score || meta.defaultScore;
    doc.setTextColor(124, 58, 237);
    doc.setFontSize(9.5);
    doc.text(`Score / Verdict: ${scoreDisplay}`, pageWidth - 70, y + 5);

    y += 10;

    // Agent Analysis Text
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);

    let summaryText = "Candidate profile evaluated against domain benchmarks.";
    if (typeof agentData === 'string') {
      summaryText = agentData;
    } else if (agentData.summary) {
      summaryText = agentData.summary;
    } else if (agentData.project_evaluation) {
      summaryText = agentData.project_evaluation;
    } else if (agentData.timeline_analysis) {
      summaryText = agentData.timeline_analysis;
    }

    const splitSummary = doc.splitTextToSize(`• Analysis: ${summaryText}`, pageWidth - 36);
    splitSummary.forEach((line: string) => {
      checkAddPage(6);
      doc.text(line, 18, y);
      y += 4.5;
    });

    // Strengths / Key Findings if present
    if (agentData.strengths && Array.isArray(agentData.strengths) && agentData.strengths.length > 0) {
      checkAddPage(6);
      doc.setFont('helvetica', 'bold');
      doc.text(`• Key Strengths: ${agentData.strengths.slice(0, 2).join('; ')}`, 18, y);
      doc.setFont('helvetica', 'normal');
      y += 4.5;
    }

    // Recommendations if present
    if (agentData.recommendations && Array.isArray(agentData.recommendations) && agentData.recommendations.length > 0) {
      checkAddPage(6);
      doc.text(`• Recommendations: ${agentData.recommendations.slice(0, 2).join('; ')}`, 18, y);
      y += 4.5;
    }

    y += 4;
  });

  // FINAL SECTION: SUPERVISOR FINAL EVALUATION
  checkAddPage(45);

  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(15, y, pageWidth - 30, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Supervisor Final Evaluation', 18, y + 5.5);
  y += 13;

  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Candidate Assessment:', 18, y); y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.text(`Candidate demonstrates strong alignment for ${targetRole} at ${companyName} with an overall readiness score of ${readinessScore}/100.`, 18, y); y += 7;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Top 5 Priority Improvement Areas:', 18, y); y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  
  const defaultImprovements = [
    "Incorporate quantitative STAR metrics (e.g. reduced latency by 45%) into experience bullet points.",
    "Complete cloud infrastructure & Docker containerization hands-on labs.",
    "Add architecture diagram and live deployment links to flagship GitHub projects.",
    "Execute weekly recruiter outreach using Communication Intelligence templates.",
    "Practice mock technical interview screens targeting core System Design concepts."
  ];

  const improvements = report.recommendations && report.recommendations.length >= 3 ? report.recommendations : defaultImprovements;
  improvements.slice(0, 5).forEach((imp: string, idx: number) => {
    checkAddPage(6);
    doc.text(`${idx + 1}. ${imp}`, 22, y);
    y += 5;
  });

  // FOOTER
  const totalPages = (doc as any).getNumberOfPages ? (doc as any).getNumberOfPages() : 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`CampusOS AI 111-Department & 1,111-Agent Platform | Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
  }

  doc.save(`CampusOS_AI_Scored_Career_Report_${Date.now()}.pdf`);
}
